### PR TITLE
Counting

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
~~Still need to add partitioning~~ done

**Comment by 9il** [comment]
@yannick counting was replaced with HLL++. requires hll-d 0.1.3, it is in code.dlang.org queue for update

**Comment by yannick** [comment]
@9il  is this finished?

**Comment by 9il** [comment]
@yannick  Yes, rebased and updated now.

**Comment by yannick** [comment]
@9il is it much effort to allow custom naming of the output and move everything into 1 output element? 
`--counter "myResult1:a.b&d" --counter "myResult2:a"`
-->
```
{ "myResult1": 123, "myResult2": 3333}
```

**Comment by 9il** [comment]
> @9il is it much effort to allow custom naming of the output and move everything into 1 output element?
> --counter "myResult1:a.b&d" --counter "myResult2:a"
> -->
> 
> { "myResult1": 123, "myResult2": 3333}

Done

**Pull request merged**
